const now = new Date();

const transaccionesMockup = [
  {
    id: 1,
    categoria: "Comida",
    monto: 400,
    fecha: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1),
    imagen: "food",
    type: "income",
  },
  {
    id: 2,
    categoria: "Transporte",
    monto: -400,
    fecha: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 2),
    imagen: "car",
    type: "expense",
  },
  {
    id: 3,
    categoria: "Café",
    monto: -400,
    fecha: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 2),
    imagen: "coffe",
    type: "expense",
  },
  {
    id: 4,
    categoria: "Salario",
    monto: 3000,
    fecha: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 3),
    imagen: "briefcase",
    type: "income",
  },
  {
    id: 5,
    categoria: "Compras",
    monto: -150,
    fecha: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 3),
    imagen: "cart-shopping",
    type: "expense",
  },
  {
    id: 6,
    categoria: "Entretenimiento",
    monto: -75,
    fecha: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 4),
    imagen: "party",
    type: "expense",
  },
  {
    id: 7,
    categoria: "Salud",
    monto: -200,
    fecha: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 5),
    imagen: "pills",
    type: "expense",
  },
  {
    id: 8,
    categoria: "Inversión",
    monto: 1000,
    fecha: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 7),
    imagen: "briefcase",
    type: "income",
  },
  {
    id: 9,
    categoria: "Facturas",
    monto: -500,
    fecha: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 7),
    imagen: "house",
    type: "expense",
  },
  {
    id: 10,
    categoria: "Viaje",
    monto: -1200,
    fecha: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 14),
    imagen: "plane",
    type: "expense",
  },
  {
    id: 11,
    categoria: "Regalos",
    monto: -50,
    fecha: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 14),
    imagen: "giftbox",
    type: "expense",
  },
  {
    id: 12,
    categoria: "Suscripciones",
    monto: -15,
    fecha: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 21),
    imagen: "mobile-app",
    type: "expense",
  },
  {
    id: 13,
    categoria: "Ropa",
    monto: -120,
    fecha: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 21),
    imagen: "high-heels",
    type: "expense",
  },
  {
    id: 14,
    categoria: "Hogar",
    monto: -300,
    fecha: new Date(now.getFullYear(), now.getMonth() - 1, now.getDate()),
    imagen: "house",
    type: "expense",
  },
  {
    id: 15,
    categoria: "Mascotas",
    monto: -80,
    fecha: new Date(now.getFullYear(), now.getMonth() - 1, now.getDate()),
    imagen: "tortoiseshell",
    type: "expense",
  },
  {
    id: 16,
    categoria: "Freelance",
    monto: 750,
    fecha: new Date(now.getFullYear(), now.getMonth() - 1, now.getDate()),
    imagen: "briefcase",
    type: "income",
  },
  {
    id: 17,
    categoria: "Educación",
    monto: -250,
    fecha: new Date(now.getFullYear(), now.getMonth() - 1, now.getDate()),
    imagen: "mortarboard",
    type: "expense",
  },
  {
    id: 18,
    categoria: "Otros",
    monto: -25,
    fecha: new Date(now.getFullYear(), now.getMonth() - 1, now.getDate()),
    imagen: "package",
    type: "expense",
  },
];
export default transaccionesMockup;
