const transaccionesMackup = [
  {
    id: 1,
    categoria: "Comida",
    monto: 400,
    fecha: "hace 1 día",
    imagen: "https://storage.googleapis.com/tagjs-prod.appspot.com/v1/krSnDOWpDM/uos1zoxp_expires_30_days.png",
    type: "income",
  },
  {
    id: 2,
    categoria: "Transporte",
    monto: -400,
    fecha: "hace 2 días",
    imagen: "https://storage.googleapis.com/tagjs-prod.appspot.com/v1/krSnDOWpDM/hq8sesz7_expires_30_days.png",
    type: "expense",
  },
  {
    id: 3,
    categoria: "Café",
    monto: -400,
    fecha: "hace 2 días",
    imagen: "https://storage.googleapis.com/tagjs-prod.appspot.com/v1/krSnDOWpDM/hq8sesz7_expires_30_days.png",
    type: "expense",
  },
  {
    id: 4,
    categoria: "Salario",
    monto: 3000,
    fecha: "hace 3 días",
    imagen: "https://storage.googleapis.com/tagjs-prod.appspot.com/v1/krSnDOWpDM/uos1zoxp_expires_30_days.png",
    type: "income",
  },
  {
    id: 5,
    categoria: "Compras",
    monto: -150,
    fecha: "hace 3 días",
    imagen: "https://storage.googleapis.com/tagjs-prod.appspot.com/v1/krSnDOWpDM/hq8sesz7_expires_30_days.png",
    type: "expense",
  },
  {
    id: 6,
    categoria: "Entretenimiento",
    monto: -75,
    fecha: "hace 4 días",
    imagen: "https://storage.googleapis.com/tagjs-prod.appspot.com/v1/krSnDOWpDM/hq8sesz7_expires_30_days.png",
    type: "expense",
  },
  {
    id: 7,
    categoria: "Salud",
    monto: -200,
    fecha: "hace 5 días",
    imagen: "https://storage.googleapis.com/tagjs-prod.appspot.com/v1/krSnDOWpDM/hq8sesz7_expires_30_days.png",
    type: "expense",
  },
  {
    id: 8,
    categoria: "Inversión",
    monto: 1000,
    fecha: "hace 1 semana",
    imagen: "https://storage.googleapis.com/tagjs-prod.appspot.com/v1/krSnDOWpDM/uos1zoxp_expires_30_days.png",
    type: "income",
  },
  {
    id: 9,
    categoria: "Facturas",
    monto: -500,
    fecha: "hace 1 semana",
    imagen: "https://storage.googleapis.com/tagjs-prod.appspot.com/v1/krSnDOWpDM/hq8sesz7_expires_30_days.png",
    type: "expense",
  },
  {
    id: 10,
    categoria: "Viaje",
    monto: -1200,
    fecha: "hace 2 semanas",
    imagen: "https://storage.googleapis.com/tagjs-prod.appspot.com/v1/krSnDOWpDM/hq8sesz7_expires_30_days.png",
    type: "expense",
  },
  {
    id: 11,
    categoria: "Regalos",
    monto: -50,
    fecha: "hace 2 semanas",
    imagen: "https://storage.googleapis.com/tagjs-prod.appspot.com/v1/krSnDOWpDM/hq8sesz7_expires_30_days.png",
    type: "expense",
  },
  {
    id: 12,
    categoria: "Suscripciones",
    monto: -15,
    fecha: "hace 3 semanas",
    imagen: "https://storage.googleapis.com/tagjs-prod.appspot.com/v1/krSnDOWpDM/hq8sesz7_expires_30_days.png",
    type: "expense",
  },
  {
    id: 13,
    categoria: "Ropa",
    monto: -120,
    fecha: "hace 3 semanas",
    imagen: "https://storage.googleapis.com/tagjs-prod.appspot.com/v1/krSnDOWpDM/hq8sesz7_expires_30_days.png",
    type: "expense",
  },
  {
    id: 14,
    categoria: "Hogar",
    monto: -300,
    fecha: "hace 1 mes",
    imagen: "https://storage.googleapis.com/tagjs-prod.appspot.com/v1/krSnDOWpDM/hq8sesz7_expires_30_days.png",
    type: "expense",
  },
  {
    id: 15,
    categoria: "Mascotas",
    monto: -80,
    fecha: "hace 1 mes",
    imagen: "https://storage.googleapis.com/tagjs-prod.appspot.com/v1/krSnDOWpDM/hq8sesz7_expires_30_days.png",
    type: "expense",
  },
  {
    id: 16,
    categoria: "Freelance",
    monto: 750,
    fecha: "hace 1 mes",
    imagen: "https://storage.googleapis.com/tagjs-prod.appspot.com/v1/krSnDOWpDM/uos1zoxp_expires_30_days.png",
    type: "income",
  },
  {
    id: 17,
    categoria: "Educación",
    monto: -250,
    fecha: "hace 1 mes",
    imagen: "https://storage.googleapis.com/tagjs-prod.appspot.com/v1/krSnDOWpDM/hq8sesz7_expires_30_days.png",
    type: "expense",
  },
  {
    id: 18,
    categoria: "Otros",
    monto: -25,
    fecha: "hace 1 mes",
    imagen: "https://storage.googleapis.com/tagjs-prod.appspot.com/v1/krSnDOWpDM/hq8sesz7_expires_30_days.png",
    type: "expense",
  },
];
export default transaccionesMackup;